made some changes
tempus-colab/goalify-client pull request #13
Opened 2024-09-26 17:34 UTC by Jessica-Uriostegui

created editgoal page in pages/goals/edit, goalform page moved it to pages/goals/new

2024-09-26 20:39 UTC, Lihemen requested changes

2024-09-26 20:39 UTC, Lihemen commented on .husky/pre-commit
> +npm run lint
This command is unnecessary.

The project is already being linted and formatted via [biome](https://biomejs.dev/)

The lint staged runs biome's linter and formatter

2024-09-26 20:39 UTC, Lihemen commented on src/pages/goals/edit/EditGoal.css
> +.top-right-button {
This can be written in tailwind as this `absolute right-4 top-4 z-10`

2024-09-26 20:39 UTC, Lihemen commented on src/pages/goals/edit/index.tsx
> +  const [goal, setGoal] = useState<string>("");
react-hook-form as a separate library is a bit of an overkill.

Mantine already uses this under the hood, so you can 

import {useForm} from "@mantine/forms"

Also the form can be initialized with default values, so no need for the multiple use states.

Furthermore, data fetching and/or syncing should not be done in a useEffect

2024-09-26 20:39 UTC, Lihemen commented on src/pages/goals/edit/index.tsx
> +  const { id } = useParams();
This id will always be undefined.

Reason is displayed in the comment for the router.tsx

2024-09-26 20:39 UTC, Lihemen commented on src/pages/goals/new/GoalForm.css
> +    position: absolute;
This can be written in tailwind, just like EditGoal.css

2024-09-26 20:39 UTC, Lihemen commented on src/routes.tsx
> +        path: "EditGoal",
By defining the edit goal route this way, the route will only match as /editgoal

It would not be possible to dynamically derive the id of the goal being edited from URL as this url /:id/editgoal is undefined.

I would suggest leaving the urls in the router file as is, 

Reason:
URLs should be verbose and grouped by domains. Per REST standards, all routes that deal with a resource should be prefaced with that resource title, e.g /users, /users/:id, /users/me, /users/:id/edit

2024-09-26 20:39 UTC, Lihemen commented on tsconfig.json
> +      "@features/*": ["features/*"],
All the relative routes in the project are prefaced with the name of the folders they belong to, without any added prefixes. e.g features/.... lib/.... pages/....

For the sake of consistent resolution.

2024-09-26 20:39 UTC, Lihemen commented on tsconfig.node.json
> +    "noEmit": false,
There is no current need to emit a declaration or compiled javascript in production seeing as the application is being bundled as an SPA not a library bundle

2024-09-26 20:39 UTC, Lihemen commented on tsconfig.app.json
> +    "emitDeclarationOnly": true,
The application is being bundled as an SPA not a library, there is no particular need for a .d.ts to be compiled with the final application.

2024-09-26 20:39 UTC, Lihemen commented on src/pages/goals/new/index.tsx
> +import { useForm, Controller } from "react-hook-form";
use the 

import {useForm} from "@mantine/forms"

It's more suited for the mantine components

2024-09-26 20:39 UTC, Lihemen commented on src/features/navigation/provider/index.tsx
> +      {!isGoalFormPage && !isEditGoalPage && <TopNavigation />}
A full page modal or drawer would overlay the application. In that scenario, there is no need to conditionally render the navigations.

2024-09-26 20:39 UTC, Lihemen commented on src/features/navigation/mobile/top.navigation.tsx
> +        <div
Per MDN standards, onPress should not be passed to elements that are not default pressable e.g buttons and inputs.

2024-09-26 20:39 UTC, Lihemen commented on package.json
> +    "typescript-eslint": "^8.7.0",
biomejs is the linter. No need for eslint

Biome is lightweight and 6 times faster than eslint and prettier

2024-09-26 20:39 UTC, Lihemen commented on package.json
> +    "prettier": "^3.3.3",
biomejs is the formatter

It is lightweight and 6 times faster than prettier

2024-09-26 20:39 UTC, Lihemen commented on package-lock.json
The default configured package manager in the repo and on render is [pnpm](https://pnpm.io/installation)

Consider downloading it to keep the `pnpm-lock.yml` up to date

2024-09-27 17:06 UTC, Jessica-Uriostegui commented on package.json
> +    "prettier": "^3.3.3",
Sounds good,

2024-09-27 17:06 UTC, Jessica-Uriostegui commented on package.json
> +    "typescript-eslint": "^8.7.0",
ok, sounds good

2024-09-27 17:06 UTC, Jessica-Uriostegui commented on src/features/navigation/mobile/top.navigation.tsx
> +        <div
I was unaware of this thank you for the information I will change it.

2024-09-27 17:07 UTC, Jessica-Uriostegui commented on src/features/navigation/provider/index.tsx
> +      {!isGoalFormPage && !isEditGoalPage && <TopNavigation />}
I think with drawer it can look over crowded and I don't like how it looks I think it works fine how it. It looks cleaner this way.

2024-09-27 17:07 UTC, Jessica-Uriostegui commented on src/pages/goals/new/GoalForm.css
> +    position: absolute;
Same as the first one.

2024-09-27 17:07 UTC, Jessica-Uriostegui commented on src/pages/goals/edit/index.tsx
> +  const { id } = useParams();
yes, I know I was testing something. I will remove it.

2024-09-27 17:07 UTC, Jessica-Uriostegui commented on src/pages/goals/edit/EditGoal.css
> +.top-right-button {
I was tested some code I had resolved it already and I did remove the file and we don't need this code it works fine.

2024-09-27 17:07 UTC, Jessica-Uriostegui commented on .husky/pre-commit
> +npm run lint
Ok, I have never worked with biome thanks for that info.

2024-09-28 01:21 UTC, Jessica-Uriostegui reviewed
What protection policies?

2024-09-30 08:06 UTC, Lihemen requested changes

2024-09-30 08:06 UTC, Lihemen commented on package.json
> +    "prepare": "husky install",
Leave as just `husky`

A script for husky has been defined in the package.json

2024-09-30 08:06 UTC, Lihemen commented on src/App.tsx
> +        <RouterProvider router={router} />
Leave the DevTools as is.

It is not bundled in production and is required in active development

2024-09-30 08:12 UTC, Lihemen commented on src/features/navigation/provider/index.tsx
> +      {!isGoalFormPage && !isEditGoalPage && <TopNavigation />}
A fullscreen drawer or fullscreen modal will not make it look crowded as it will cover the full screen.

This approach of yours is untenable. I'll tell you why

Say there is another path that requires an overlay of the entire screen, will you come and make a modification to this?And so on and so on.

The DRY pattern would mandate that you take an approach that minimises having to repeat a redundant action. So use a fullscreen modal instead to wrap the form.

2024-10-02 15:13 UTC, closed without merging