Merge Offline Database into Main
tempus-colab/goalify-client pull request #16
Opened 2024-10-03 16:55 UTC by Lihemen

# PR Template

## Description

This PR introduces the following features
1. Rollbar for error reporting
2. Sentry for crashlytics and session replays
3. RxDB as the offline database for an offline-syncable PWA
4. Hooks for performing CRUD operations with the DB (syncable with a backend API)

This PR also fixes the following issues
1. Deletes the package-lock
2. Ensures lint staged runs irrespective of OS
3. All linting and formatting issues in the project

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Test

## Related Issues

Please link to the issues this pull request addresses (if any):

- Fixes #(issue number)

## Screenshots (if applicable)

Add any relevant screenshots or GIFs to help visualize the changes (if UI/UX related).

## Checklist

Before submitting, make sure your PR meets these requirements:

- [ ] I have tested my changes locally and verified that they are working as intended.
- [ ] I have written tests for all new functionality (if applicable).
- [ ] I have updated the documentation where necessary.
- [ ] I have followed the coding style of this project.
- [ ] My PR has been reviewed by at least one peer (if applicable).
- [ ] This PR is ready for review and merge.

## Additional Context

Any other information or thoughts relevant to this PR. Consider mentioning team members for visibility.

2024-10-07 16:51 UTC, Jessica-Uriostegui requested changes

2024-10-10 17:07 UTC, Lihemen commented on src/features/goal-form/index.tsx
It’s an example of how to sync with and use the database

2024-10-10 18:01 UTC, Lihemen commented on src/features/goal-form/index.tsx
It’s an example of how to write to and sync with the database.

2024-10-10 18:33 UTC, Jessica-Uriostegui requested changes
On top navigation Add button is attached to goalform which was the name of my code page that you changed. so this goes to the page that  you called "sample page" sample page for what? also why was the name changed? why dont you change the name to your page into sample page?  why was the space added to goalform

2024-10-10 18:33 UTC, Jessica-Uriostegui commented on src/features/navigation/mobile/top.navigation.tsx
So why does this button lead to GoalForm if its just a sample ?

2024-10-11 10:40 UTC, Lihemen commented on .husky/pre-commit
This solves for that.

2024-10-11 10:42 UTC, Lihemen commented on src/pages/goals/new/index.tsx
Goal form is a generic name that doens't encapsulate anything.

NewGoal is more specific.

Also, all exports are named exports, using GoalForm for a component that connotes a new goal is not ideal.

2024-10-11 10:42 UTC, Lihemen commented on src/pages/goals/edit/index.tsx
That is the linter at work.

2024-10-11 10:44 UTC, Lihemen commented on src/features/navigation/mobile/top.navigation.tsx
Lead to what?
It leads to a path /goals/new. Have you checked the component rendered at that path?

2024-10-11 10:49 UTC, Lihemen commented
> On top navigation Add button is attached to goalform which was the name of my code page that you changed. so this goes to the page that you called "sample page" sample page for what? also why was the name changed? why dont you change the name to your page into sample page? why was the space added to goalform



@Jessica-Uriostegui the button goes to the path /goals/new. I'm trying hard to see how this is difficult to understand. This is a non-issue.

2024-10-15 21:24 UTC, closed without merging